export type OrbSignalState = 'WATCHING' | 'SIGNAL' | 'SIGNAL_UNRESOLVED' | 'REJECTED' | 'ERROR' | 'ENDED';
export interface OrbSignalCandidate { symbol:string; kind?:string; status?:string; signal:{direction:'LONG'|'SHORT'|'NONE';timestamp?:string;spot?:number;or_high?:number;or_low?:number;vwap?:number;atr?:number;volume_ratio?:number;confidence?:number;reason?:string;vwap_basis?:'volume'|'time';volume_confirmed?:boolean}; option?:{symbol:string;strike:number;expiry:string;option_type:'CE'|'PE';ltp:number;bid:number;ask:number;lot_size:number;volume:number;open_interest:number}|null; trade_plan?:{entry_premium:number;stop_premium:number;target_premium:number;quantity:number;risk_inr:number;max_loss_inr?:number;delta_is_estimated?:boolean;delta_source?:string;delta?:number|null;implied_volatility?:number|null;gamma?:number|null;theta_per_day?:number|null;vega_per_point?:number|null;underlying_entry?:number;underlying_stop?:number}|null; data_source?:'kite'|'truedata'; quote_age_s?:number|null; exchange?:string; lot_size?:number; ticket_fingerprint?:string|null; auto_block?:string|null; }
export interface OrbFeedEntry { id:string;strategy:'ORB';underlying:string;direction:'long'|'short'|null;state:OrbSignalState;spot:number|null;orbHigh:number|null;orbLow:number|null;vwap:number|null;atr:number|null;volumeRatio:number|null;optionSymbol:string|null;optionStrike:number|null;optionType:'CE'|'PE'|null;optionExpiry:string|null;optionPremium:number|null;stopPremium:number|null;targetPremium:number|null;quantity:number|null;riskInr:number|null;maxLossInr:number|null;deltaIsEstimated:boolean;deltaSource:'broker'|'implied'|'assumed'|null;delta:number|null;impliedVol:number|null;gamma:number|null;thetaPerDay:number|null;vegaPerPoint:number|null;exchange:string|null;lotSize:number|null;underlyingEntry:number|null;underlyingStop:number|null;dataSource:'kite'|'truedata'|null;quoteAgeS:number|null;reason:string|null;timestamp:string|null;
  /** How `vwap` was computed. 'time' means the feed reports no volume — every
   *  index — so the line is an unweighted mean of typical price, not a VWAP. */
  vwapBasis:'volume'|'time';
  /** Whether the participation gate was actually evaluated. False on any
   *  volume-less feed, where a 1.00x ratio is a placeholder, not a measurement. */
  volumeConfirmed:boolean;
  ticketFingerprint?:string|null;
  /** Same reason Auto would emit, so Manual shows the refusal without a second brain. */
  autoBlock?:string|null; }
function stateOf(c:OrbSignalCandidate):OrbSignalState { const s=(c.status||'').toUpperCase(); if(s==='ENDED')return 'ENDED'; if(s==='ERROR')return 'ERROR'; if(s==='REJECTED'||s==='LIQUIDITY_REJECTED')return 'REJECTED'; if(s==='SIGNAL_UNRESOLVED')return 'SIGNAL_UNRESOLVED'; if(c.signal.direction==='NONE')return 'WATCHING'; if(!c.option||!c.trade_plan)return 'SIGNAL_UNRESOLVED'; return 'SIGNAL'; }
export function toOrbFeedEntry(c:OrbSignalCandidate,index=0):OrbFeedEntry { const signal=c.signal,plan=c.trade_plan,option=c.option,state=stateOf(c),direction=signal.direction==='SHORT'?'short':signal.direction==='LONG'?'long':null,key=`${c.symbol}:${signal.timestamp||'live'}:${signal.direction}:${option?.symbol||'none'}`; return {id:`ORB-${key}-${index}`,strategy:'ORB',underlying:c.symbol,direction,state,spot:signal.spot??null,orbHigh:signal.or_high??null,orbLow:signal.or_low??null,vwap:signal.vwap??null,atr:signal.atr??null,volumeRatio:signal.volume_ratio??null,optionSymbol:option?.symbol??null,optionStrike:option?.strike??null,optionType:option?.option_type??null,optionExpiry:option?.expiry??null,optionPremium:option?.ltp??plan?.entry_premium??null,stopPremium:plan?.stop_premium??null,targetPremium:plan?.target_premium??null,quantity:plan?.quantity??null,riskInr:plan?.risk_inr??null,maxLossInr:plan?.max_loss_inr??null,deltaIsEstimated:plan?.delta_is_estimated===true,deltaSource:(plan?.delta_source as OrbFeedEntry['deltaSource'])??null,delta:plan?.delta??null,impliedVol:plan?.implied_volatility??null,gamma:plan?.gamma??null,thetaPerDay:plan?.theta_per_day??null,vegaPerPoint:plan?.vega_per_point??null,exchange:c.exchange??null,lotSize:c.lot_size??option?.lot_size??null,underlyingEntry:plan?.underlying_entry??null,underlyingStop:plan?.underlying_stop??null,dataSource:c.data_source??null,quoteAgeS:c.quote_age_s??null,reason:c.auto_block||signal.reason||null,timestamp:signal.timestamp??null,vwapBasis:signal.vwap_basis==='time'?'time':'volume',volumeConfirmed:signal.volume_confirmed!==false,ticketFingerprint:c.ticket_fingerprint??null,autoBlock:c.auto_block??null}; }
/** A scan row with no signal is a FAILURE, not an absence. Dropping those made
 *  a scan where every underlying errored render as "no configured underlyings". */
function normalizeRow(row:Record<string,any>):OrbSignalCandidate|null { if(typeof row.symbol!=='string'&&typeof row.underlying!=='string')return null;
  if(!row.signal) return {symbol:String(row.symbol||row.underlying),status:row.status||'error',signal:{direction:'NONE',reason:String(row.error||row.trade_error||'scan failed'),vwap_basis:row.vwap_basis,volume_confirmed:row.volume_confirmed,timestamp:row.timestamp_ms?new Date(row.timestamp_ms).toISOString():undefined},option:null,trade_plan:null,data_source:row.data_source,quote_age_s:row.quote_age_s,exchange:row.exchange,lot_size:row.lot_size,ticket_fingerprint:row.ticket_fingerprint??null,auto_block:row.auto_block??null}; const trade=row.trade||null; const contract=trade?.contract||null; return {symbol:String(row.symbol||row.underlying),status:row.status,signal:{...row.signal,spot:row.signal.spot??row.spot,timestamp:row.signal.timestamp||(row.timestamp_ms?new Date(row.timestamp_ms).toISOString():undefined)},option:contract?{symbol:String(contract.symbol||''),strike:Number(contract.strike||0),expiry:String(contract.expiry||''),option_type:contract.option_type,ltp:Number(contract.ltp||0),bid:Number(contract.bid||0),ask:Number(contract.ask||0),lot_size:Number(contract.lot_size||1),volume:Number(contract.volume||0),open_interest:Number(contract.open_interest||0)}:null,trade_plan:trade?{entry_premium:Number(trade.entry_premium||0),stop_premium:Number(trade.stop_premium||0),target_premium:Number(trade.target_premium||0),quantity:Number(trade.quantity||0),risk_inr:Number(trade.risk_inr||0),max_loss_inr:Number(trade.max_loss_inr||0),delta_is_estimated:trade.delta_is_estimated===true,delta_source:trade.delta_source,delta:trade.delta??null,implied_volatility:trade.implied_volatility??null,gamma:trade.gamma??null,theta_per_day:trade.theta_per_day??null,vega_per_point:trade.vega_per_point??null,underlying_entry:Number(trade.underlying_entry||0),underlying_stop:Number(trade.underlying_stop||0)}:null,data_source:row.data_source,quote_age_s:row.quote_age_s,exchange:row.exchange,lot_size:row.lot_size,ticket_fingerprint:row.ticket_fingerprint??null,auto_block:row.auto_block||row.reason||null}; }
export function toOrbFeedEntries(payload:unknown):OrbFeedEntry[] { if(!payload||typeof payload!=='object')return []; const p=payload as Record<string,unknown>; const rows=Array.isArray(p.candidates)?p.candidates:Array.isArray(p.signals)?p.signals:[]; return rows.map(x=>x&&typeof x==='object'?normalizeRow(x as Record<string,any>):null).filter((x):x is OrbSignalCandidate=>x!==null).map((x,i)=>toOrbFeedEntry(x,i)); }
